# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b6e8915efa9ccccff2633aaea1295fa341ceda188230cce1ec973445fe0557237d6f0c4b4373a7c106808421f93ccd7b74b00069eaf5d435ba5b5d98b0e51d9

test:
  secret_key_base: 2a1ab6f82b9cca2dd00c71f7f167a95bc6c5bb725202488e578733eece936f0adf0eca4360d3b68a9aead6a74f5ee7365d3a1cc065cd32db369f8ca17e7e1f74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
